# Generated by Django 3.1.2 on 2020-10-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='type',
            field=models.ManyToManyField(to='User.DoctorTypeModel'),
        ),
    ]
