# Generated by Django 3.1.6 on 2021-02-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answers',
            field=models.ManyToManyField(blank=True, to='forum.AnswerModel'),
        ),
    ]
