# Generated by Django 3.1.2 on 2020-10-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
